# Generated by Django 5.1.5 on 2025-01-25 18:24

import mydanceclub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=mydanceclub.models.generate_uuid,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
