# Generated by Django 5.1.5 on 2025-01-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
