# Generated by Django 5.1.5 on 2025-01-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="location",
            name="description",
        ),
        migrations.AddField(
            model_name="location",
            name="google_place_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="location",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
