# Generated by Django 5.1.5 on 2025-02-05 21:23

import django.core.validators
import django.db.models.deletion
import mydanceclub.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DanceClassReview",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=mydanceclub.models.generate_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group_size",
                    models.FloatField(
                        help_text="Rating (-10 to 10) of the group size. Where -10 is the worst, 0 is perfect and 10 is too much",
                        validators=[
                            django.core.validators.MinValueValidator(-10),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "level",
                    models.FloatField(
                        help_text="Rating (-10 to 10) of the level of the class. Where -10 is the worst, 0 is perfect and 10 is too much",
                        validators=[
                            django.core.validators.MinValueValidator(-10),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "engagement",
                    models.FloatField(
                        help_text="Rating (-10 to 10) of the engagement of the class. Where -10 is the worst and 10 is the best",
                        validators=[
                            django.core.validators.MinValueValidator(-10),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "teaching_pace",
                    models.FloatField(
                        help_text="Rating (-10 to 10) of the teaching pace of the class. Where -10 is the worst, 0 is perfect and 10 is too much",
                        validators=[
                            django.core.validators.MinValueValidator(-10),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        help_text="Overall rating (1-5) for the dance class experience",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="General comments and observations about the dance class experience"
                    ),
                ),
                (
                    "dance_class",
                    models.ForeignKey(
                        help_text="The dance class being reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="classes.danceclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstructorReview",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=mydanceclub.models.generate_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "move_breakdown",
                    models.FloatField(
                        help_text="Rating (-10 to 10) of the instructor's move breakdown. Where -10 is the worst, 0 is perfect and 10 is too much",
                        validators=[
                            django.core.validators.MinValueValidator(-10),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "individual_approach",
                    models.FloatField(
                        help_text="Rating (-10 to 10) of the instructor's individual approach. Where -10 is the worst, 0 is perfect and 10 is too much",
                        validators=[
                            django.core.validators.MinValueValidator(-10),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "posture_correction_ability",
                    models.FloatField(
                        help_text="Rating (1 to 10) of the instructor's posture correction ability. Where 1 is the worst and 10 is the best",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "communication_and_feedback",
                    models.FloatField(
                        help_text="Rating (1 to 10) of the instructor's communication and feedback. Where 1 is the worst and 10 is the best",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "patience_and_encouragement",
                    models.FloatField(
                        help_text="Rating (1 to 10) of the instructor's patience and encouragement. Where 1 is the worst and 10 is the best",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "motivation_and_energy",
                    models.FloatField(
                        help_text="Rating (1 to 10) of the instructor's motivation and energy. Where 1 is the worst and 10 is the best",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        help_text="Overall rating (1-5) for the dance class experience",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="General comments and observations about the dance class experience"
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        help_text="The instructor being reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LocationReview",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=mydanceclub.models.generate_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cleanness",
                    models.FloatField(
                        help_text="Rating (1 to 10) of the facilities cleanliness. Where 1 is the worst and 10 is the best",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "general_look",
                    models.FloatField(
                        help_text="Rating (1 to 10) of the general look of the facilities. Where 1 is the worst and 10 is the best",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "acustic_quality",
                    models.FloatField(
                        help_text="Rating (1 to 10) of the acustic quality of the facilities. Where 1 is the worst and 10 is the best",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "additional_facilities",
                    models.FloatField(
                        help_text="Rating (1 to 10) of the additional facilities of the facilities. Where 1 is the worst and 10 is the best",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        help_text="Rating (-10 to 10) of the temperature of the facilities. Where -10 is the worst and 10 is the best",
                        validators=[
                            django.core.validators.MinValueValidator(-10),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "lighting",
                    models.FloatField(
                        help_text="Rating (-10 to 10) of the lighting of the facilities. Where -10 is the worst and 10 is the best",
                        validators=[
                            django.core.validators.MinValueValidator(-10),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        help_text="Overall rating (1-5) for the dance class experience",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="General comments and observations about the dance class experience"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="The location being reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities_reviews",
                        to="classes.location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=mydanceclub.models.generate_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anonymous_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name for anonymous reviews. Required if user is not provided",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the review has been verified by staff",
                    ),
                ),
                (
                    "dance_class_stats",
                    models.OneToOneField(
                        help_text="Review of the dance class experience",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="reviews.danceclassreview",
                    ),
                ),
                (
                    "facilities_stats",
                    models.OneToOneField(
                        help_text="Review of the supporting facilities and amenities",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="reviews.locationreview",
                    ),
                ),
                (
                    "instructor_stats",
                    models.OneToOneField(
                        help_text="Review of the instructor's teaching approach",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="reviews.instructorreview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user submitting the review. Can be null for anonymous reviews",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
