# Generated by Django 5.1.5 on 2025-02-02 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="danceclassreview",
            name="engagement",
            field=models.FloatField(
                help_text="Rating (-10 to 10) of the engagement of the class. Where -10 is the worst and 10 is the best",
                validators=[
                    django.core.validators.MinValueValidator(-10),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
