# Generated by Django 5.1.5 on 2025-02-02 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_genre_alter_reviewverification_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewverification",
            name="review",
        ),
        migrations.AddField(
            model_name="review",
            name="verification",
            field=models.OneToOneField(
                blank=True,
                help_text="Verification details for this review",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_review",
                to="reviews.reviewverification",
            ),
        ),
    ]
