# Generated by Django 5.1.5 on 2025-01-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialschedule",
            name="replaced_schedule_date",
            field=models.DateField(
                blank=True,
                help_text="The specific date of the recurring schedule being replaced",
                null=True,
            ),
        ),
    ]
