# Generated by Django 5.1.5 on 2025-01-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_specialschedule_replaced_schedule_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialschedule",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="For explaining why this special schedule exists",
                null=True,
            ),
        ),
    ]
